INSERT INTO country (name, capital, region, subregion, area) VALUES ('Spain', 'Madrid', 'Europe', 'Southern Europe', 505992.0);
INSERT INTO country (name, capital, region, subregion, area) VALUES ('Germany', 'Berlin', 'Europe', 'Western Europe', 357114.0);
INSERT INTO country (name, capital, region, subregion, area) VALUES ('France', 'Paris', 'Europe', 'Western Europe', 640679.0);
INSERT INTO country (name, capital, region, subregion, area) VALUES ('Italy', 'Rome', 'Europe', 'Southern Europe', 301340.0);
INSERT INTO country (name, capital, region, subregion, area) VALUES ('Portugal', 'Lisbon', 'Europe', 'Southern Europe', 92090.0);
INSERT INTO country (name, capital, region, subregion, area) VALUES ('United Kingdom', 'London', 'Europe', 'Northern Europe', 242900.0);
INSERT INTO country (name, capital, region, subregion, area) VALUES ('United States', 'Washington', 'Americas', 'Northern America', 9372610.0);
INSERT INTO country (name, capital, region, subregion, area) VALUES ('Canada', 'Ottawa', 'Americas', 'Northern America', 9984670.0);
INSERT INTO country (name, capital, region, subregion, area) VALUES ('Mexico', 'Mexico City', 'Americas', 'Central America', 1964375.0);
INSERT INTO country (name, capital, region, subregion, area) VALUES ('Brazil', 'Brasilia', 'Americas', 'South America', 8515767.0);